services:
  push-service:
    image: ghcr.io/bystrek/push-service:latest
    env_file: .env
    volumes:
      - push_service_data:/app/data
    restart: unless-stopped

  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  push_service_data:
