services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - open_webui_data:/app/backend/data
    restart: unless-stopped

  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  open_webui_data:
